services:
  mysql:
    image: mysql:latest
    container_name: mysql
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    #      MYSQL_DATABASE: test
    #      MYSQL_USER: test
    #      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql